defaults: &defaults
  mailer:
    notifications_email: "notifications@write_up.com"
    domain_name: "write_up.com"

production:
  <<: *defaults
  db_index: 0

staging:
  <<: *defaults
  db_index: 0

integration:
  <<: *defaults
  db_index: 0

development:
  <<: *defaults
  db_index: 1

test:
  <<: *defaults
  db_index: 2
